### ISSUE TITLE
mouse Button4/5 dont work?

### ISSUE THREAD

**Issue by sebastinas** [pwmt/girara#21]
*On GitLab by @djv on Jul 30, 2020, 10:53*

---

Such commands seems have no effect:
```
map <Button4> jumplist forward
map <Button5> jumplist backward
```

while Button2/3 work good.

**Comment by sebastinas** [comment]
moved from zathura#170

**Comment by sebastinas** [comment]
*On GitLab by @amo on Nov 7, 2022, 03:15*

---

mentioned in issue zathura#312

**Comment by morganmay** [comment]
I am still experiencing this bug in zathura 0.5.8 with girara 0.4.4.

```
map <Button4> jumplist forward
map <Button5> jumplist backward
```
has no effect.

```
map <Button2> jumplist forward
map <Button3> jumplist backward
```
works.

This is a pity, because buttons 4 and 5 are the ones I want to use.

**Comment by morganmay** [comment]
Of course, shortly after I posted the above, I figured out the problem. Despite my mouse having 5 buttons, `xev` revealed that they are not numbered 1-5, but rather 1-3 and 8-9. in the end, this config worked:
```
map <Button9> jumplist forward
map <Button8> jumplist backward
```

**Comment by fmorroni** [comment]
Hi, was this actually fixed? I'm still having this problem. `Button4` and `Button5` are the scroll wheel up/down keybinds, but they aren't working for me. I'm trying to set up horizontal scrolling with `shift+scroll wheel` like this:
```config
map <S-Button4> scroll left
map <S-Button5> scroll right
```
but it does nothing. Mapping without modifier, which should override the default scroll behavior, also does nothing.

I'm on version:
```bash
❯ zathura --version
zathura 2026.02.22
girara 2026.02.04 (runtime: 2026.02.04)
(plugin) pdf-mupdf (2026.2.3) (/usr/lib/zathura/libpdf-mupdf.so)
```
